name: go_router_sugar
description: Zero-effort file-based routing for Flutter with go_router. Automatically generates routing configuration from your file structure.
version: 1.0.0
homepage: https://github.com/mukhbit0/go_router_sugar
repository: https://github.com/mukhbit0/go_router_sugar
issue_tracker: https://github.com/mukhbit0/go_router_sugar/issues
documentation: https://github.com/mukhbit0/go_router_sugar#readme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  analyzer: ^7.7.1
  build: ^3.0.0
  flutter:
    sdk: flutter
  glob: ^2.1.2
  go_router: ^16.1.0
  meta: ^1.11.0
  path: ^1.9.0
  source_gen: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  test: ^1.25.2

# Executable commands
executables:
  go_router_sugar: generate
  go_router_sugar_watch: watch