name: go_router_sugar
description: The Simplest Flutter Routing Ever! Revolutionary CLI with interactive wizard, auto-magic watch mode, beautiful route visualization, and unified architecture.
version: 1.2.1
homepage: https://github.com/mukhbit0/go_router_sugar
repository: https://github.com/mukhbit0/go_router_sugar
issue_tracker: https://github.com/mukhbit0/go_router_sugar/issues
documentation: https://github.com/mukhbit0/go_router_sugar#readme

topics:
  - routing
  - go-router
  - navigation
  - code-generation
  - file-based-routing

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  analyzer: ^7.7.1
  args: ^2.5.0
  build: ^3.0.0
  flutter:
    sdk: flutter
  glob: ^2.1.2
  go_router: ^16.1.0
  io: ^1.0.4
  meta: ^1.11.0
  path: ^1.9.0
  source_gen: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  test: ^1.25.2

# Executable commands
executables:
  go_router_sugar: go_router_sugar