// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by go_router_sugar
// ignore_for_file: type=lint, unused_import, directives_ordering

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

import 'package:minimal_example/pages/about_page.dart';
import 'package:minimal_example/pages/home_page.dart';

/// Generated route constants
abstract class Routes {
  /// Route: /about
  static const String about = '/about';

  /// Route: /home
  static const String home = '/home';
}

/// Auto-generated router configuration
class AppRouter {
  AppRouter._();

  /// The configured GoRouter instance
  static final GoRouter instance = GoRouter(
    routes: <RouteBase>[
      GoRoute(
        path: '/about',
        builder: (BuildContext context, GoRouterState state) {
          return const AboutPage();
        },
      ),
      GoRoute(
        path: '/home',
        builder: (BuildContext context, GoRouterState state) {
          return const HomePage();
        },
      ),
    ],
  );

  /// Access the router configuration
  static GoRouter get router => instance;
}

/// Type-safe navigation helpers
extension AppRouterNavigation on GoRouter {
  /// Navigate to /about
  void goToAbout() {
    go('/about');
  }

  /// Navigate to /about
  void pushToAbout() {
    push('/about');
  }

  /// Navigate to /home
  void goToHome() {
    go('/home');
  }

  /// Navigate to /home
  void pushToHome() {
    push('/home');
  }
}

/// Static navigation helpers
class Navigate {
  Navigate._();

  /// Navigate to /about
  static void goToAbout() {
    AppRouter.instance.go('/about');
  }

  /// Navigate to /about
  static void pushToAbout() {
    AppRouter.instance.push('/about');
  }

  /// Navigate to /home
  static void goToHome() {
    AppRouter.instance.go('/home');
  }

  /// Navigate to /home
  static void pushToHome() {
    AppRouter.instance.push('/home');
  }
}
