// 🍬 GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Go Router Sugar - The Simplest Flutter Routing Ever!
//
// 🎯 This file provides a complete routing solution with:
//   ✅ Type-safe navigation
//   ✅ Zero string-based routing
//   ✅ Full parameter validation
//   ✅ Beautiful IntelliSense support
//
// 📖 Usage:
//   Navigate.toHome();
//   Navigate.toProduct(id: "123", category: "electronics");
//   context.goToHome();
//   context.goToProduct(id: "123");
//
// 🚀 Say goodbye to: context.go("/products/123?category=electronics")
// 🎉 Say hello to:   Navigate.toProduct(id: "123", category: "electronics")

import 'package:flutter/material.dart';
import 'package:go_router_sugar/go_router_sugar.dart';

import 'pages/home_page.dart';
import 'pages/products/[id]_page.dart';
import 'pages/products/list_page.dart';

/// 🍬 Your App's Complete Routing Configuration
///
/// Generated from your page files with zero configuration required.
/// Just add this to your MaterialApp.router(routerConfig: AppRouter.router)
class AppRouter {
  AppRouter._(); // Private constructor - use static router instance

  /// 🎯 The complete GoRouter configuration for your app
  ///
  /// Includes 3 routes with full type safety and parameter validation.
  static final GoRouter router = GoRouter(
    initialLocation: '/',
    routes: [
      GoRoute(
        path: '/home',
        builder: (context, state) {
          return const HomePage();
        },
      ),
      GoRoute(
        path: '/products/:id',
        builder: (context, state) {
          return ProductPage(id: state.pathParameters['id'] ?? '');
        },
      ),
      GoRoute(
        path: '/products/list',
        builder: (context, state) {
          return const ListPage();
        },
      ),
    ],
  );
}

/// 🗂️ Route Path Constants
///
/// Use these constants instead of hardcoded strings.
/// Example: context.go(Routes.home) instead of context.go("/home")
class Routes {
  Routes._(); // Private constructor

  /// 📄 Home page
  static const String home = '/home';

  /// 🔍 Product page for specific id
  static const String productsId = '/products/:id';

  /// 📄 List page
  static const String productsList = '/products/list';

  /// 📋 All available routes in your app
  static const List<String> all = [
    home,
    productsId,
    productsList,
  ];
}

/// 🚀 Type-Safe Navigation API
///
/// Navigate to any page with full type safety and parameter validation.
/// No more string-based routing or runtime errors!
///
/// Example:
///   Navigate.toHome();
///   Navigate.toProduct(id: "123", category: "electronics");
class Navigate {
  Navigate._(); // Private constructor

  /// 🧭 The global navigator key for programmatic navigation
  static final GlobalKey<NavigatorState> _navigatorKey =
      GlobalKey<NavigatorState>();

  /// Access to the navigator key (for advanced use cases)
  static GlobalKey<NavigatorState> get navigatorKey => _navigatorKey;

  /// 📄 Home page
  static void toHome() {
    final context = _navigatorKey.currentContext;
    if (context == null) {
      throw StateError(
          'Navigator context is null. Make sure AppRouter.router is used in MaterialApp.router');
    }
    context.go('/home');
  }

  /// 🔍 Product page for specific id
  ///
  /// [id] - Required parameter
  static void toProduct({
    required String id,
  }) {
    final context = _navigatorKey.currentContext;
    if (context == null) {
      throw StateError(
          'Navigator context is null. Make sure AppRouter.router is used in MaterialApp.router');
    }
    final path = '/products/$id';
    context.go(path);
  }

  /// 📄 List page
  static void toProductsList() {
    final context = _navigatorKey.currentContext;
    if (context == null) {
      throw StateError(
          'Navigator context is null. Make sure AppRouter.router is used in MaterialApp.router');
    }
    context.go('/products/list');
  }
}

/// 🎯 BuildContext Extensions for Fluent Navigation
///
/// Use these extension methods for more idiomatic Flutter navigation.
/// Example: context.goToHome() instead of Navigate.toHome()
extension GoRouterSugarNavigation on BuildContext {
  /// 📄 Home page
  void goToHome() => Navigate.toHome();

  /// 🔍 Product page for specific id
  void goToProduct({
    required String id,
  }) =>
      Navigate.toProduct(id: id);

  /// 📄 List page
  void goToProductsList() => Navigate.toProductsList();
}
