// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by go_router_sugar 🍬

import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'pages/home_page.dart';
import 'pages/products/[id]_page.dart';
import 'pages/products/list_page.dart';

class AppRouter {
  static final GoRouter router = GoRouter(
    initialLocation: '/',
    routes: [
      GoRoute(
        path: '/home',
        builder: (context, state) {
          return const HomePage();
        },
      ),
      GoRoute(
        path: '/products/:id',
        builder: (context, state) {
          return ProductPage(id: state.pathParameters['id']!);
        },
      ),
      GoRoute(
        path: '/products/list',
        builder: (context, state) {
          return const ListPage();
        },
      ),
    ],
  );
}
